name = "blackroad-io"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "blackroad.io/*", zone_name = "blackroad.io" },
  { pattern = "www.blackroad.io/*", zone_name = "blackroad.io" }
]

[[d1_databases]]
binding = "DB"
database_name = "blackroad-os-main"
database_id = "e2c6dcd9-c21a-48ac-8807-7b3a6881c4f7"
